CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE CATEGORY (
	CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    
    PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PUBLISHER(
	PUB_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(2048) NOT NULL,
    
    PRIMARY KEY (PUB_ID)
);

CREATE TABLE BOOK(
	BOOK_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(2048),
    PRICE FLOAT NOT NULL, 
    PUB_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    
    FOREIGN KEY (PUB_ID) REFERENCES PUBLISHER(PUB_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    PRIMARY KEY (BOOK_ID)
);

CREATE TABLE MEMBER(
	MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(2048) NOT NULL,
    JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE BORROWING_BOOK(
	MEMBER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    BORROW_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DUE_DATE DATETIME,
    RETURN_DATE DATETIME,
    
    PRIMARY KEY (MEMBER_ID, BOOK_ID, BORROW_DATE),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);